### ISSUE TITLE
Suggest considering different name

### ISSUE THREAD

**Issue by zturtleman** [coltongit/iqq2#1]
ioquake3 / ioq3 (originally named _icculus.org/quake3_) is from the URL https://icculus.org/quake3/.

_icculus.org/quake2_ at the URL https://icculus.org/quake2/ also exists. Although it doesn't go by the name ioquake2 / ioq2 as far as I know. (Likely due to it ceasing development before i.o/quake3 was renamed to ioquake3.) Naming another project ioq2 seems unnecessarily confusing though. So I would suggest considering using a different name.

In any case, good luck with your Quake 2 project.

**Comment by coltongit** [comment]
Fixed by renaming to iqq2, or IQQuake2, to avoid naming problems.
